quarkus.rest-client.maya-service.url=https://pg-sandbox.paymaya.com

quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=100000
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
maya.public-key=
maya.secret-key=